-- Add image_url column to exercises table
-- This is optional - the script can use video_url field instead

ALTER TABLE public.exercises 
ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Add comment
COMMENT ON COLUMN public.exercises.image_url IS 'URL to exercise preview image generated by AI';

-- Optional: Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_exercises_image_url ON public.exercises(image_url) WHERE image_url IS NOT NULL;

